<?php
// This partial now expects these variables to be set BEFORE including it:
// - $levelConfig (array with grid_width, grid_height, walls, bombs, key, door)
// OR if not set, it will use defaults

// Default configuration
$defaultConfig = [
    'grid_width' => 12,
    'grid_height' => 12,
    'walls' => [],
    'bombs' => [],
    'key' => ['x' => 0, 'y' => 0],
    'door' => ['x' => 11, 'y' => 11]
];

// Use provided config or defaults
if (isset($levelConfig) && is_array($levelConfig)) {
    $config = $levelConfig;
} else {
    $config = $defaultConfig;
}

// Extract values
$gridWidth = (int)($config['grid_width'] ?? 12);
$gridHeight = (int)($config['grid_height'] ?? 12);
$configJson = json_encode($config);
?>

<!-- Hidden inputs for form submission -->
<input type="hidden" name="config_json" id="levelConfigJson" value="<?= htmlspecialchars($configJson) ?>">
<input type="hidden" name="grid_width" id="gridWidthInput" value="<?= $gridWidth ?>">
<input type="hidden" name="grid_height" id="gridHeightInput" value="<?= $gridHeight ?>">

<div class="mt-4">
    <h6>Level Editor</h6>

    <div class="d-flex flex-wrap gap-2 align-items-center mb-3">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-sm btn-outline-light active" data-tool="wall">Wall</button>
            <button type="button" class="btn btn-sm btn-outline-danger" data-tool="bomb">Bomb</button>
            <button type="button" class="btn btn-sm btn-outline-success" data-tool="key">Key</button>
            <button type="button" class="btn btn-sm btn-outline-warning" data-tool="door">Door</button>
            <button type="button" class="btn btn-sm btn-outline-secondary" data-tool="erase">Eraser</button>
        </div>

        <button type="button" class="btn btn-sm btn-outline-dark ms-2" id="btnClearLevel">
            Clear All
        </button>
    </div>

    <div class="text-muted small mb-3">
        Click to place: <span class="text-light">Walls</span>, 
        <span class="text-danger">Bombs</span>, 
        <span class="text-success">Key</span>, 
        <span class="text-warning">Door</span>
    </div>

    <!-- The grid container -->
    <div id="levelGrid"
         class="d-grid border border-secondary rounded p-3 bg-dark"
         style="grid-template-columns: repeat(<?= $gridWidth ?>, 34px); gap: 4px; justify-content: start;">
        <!-- Grid cells will be generated by JavaScript -->
    </div>
</div>

<script>
// Pass data to JavaScript
window.levelEditorData = {
    gridWidth: <?= $gridWidth ?>,
    gridHeight: <?= $gridHeight ?>,
    config: <?= $configJson ?>
};
</script>

<!-- Load editor JS -->
<script src="/assets/js/level-editor.js"></script>